spring:
  profiles.active : local
environment: local


## SQL config
spring.datasource.url: jdbc:mysql://localhost:3306/banking_customer_service
spring.jpa.properties.hibernate.default_schema: public
spring.datasource.username: root
spring.datasource.password: mysecretpassword
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver


#JPA
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.data.jpa.repositories.enabled: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: validate